name: Pull Request
on:
  pull_request:
    branches:
    - main

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: unit test
      uses: m3y/rust-just-action@v1
      with:
        command: test
